AG
Alyelfekyy/namlaXyaya pull request #1
Opened 2020-01-29 14:51 UTC by alynamlaa

2020-01-30 16:52 UTC, YahiaBadr requested changes

2020-01-30 16:52 UTC, YahiaBadr commented on routes/api/users.js
> +    const x=request.body;
rename x to be understandable by the reader.
Like `const body = request.body` or another better option,
`const courseName = request.body.courseName` and make the other constants for `grade` and `creditHours`.

2020-01-30 16:52 UTC, YahiaBadr commented on routes/api/users.js
> +    console.log(users)
remove the console.log. Leave the code clean.

2020-01-30 16:52 UTC, YahiaBadr commented on routes/api/users.js
> +router.put("/:username/grades",(request,response) =>{
the route must be clean and descriptive,
`/addGrades/:username`,
always leave the params at the end.

2020-01-30 17:48 UTC, YahiaBadr requested changes

2020-01-30 17:48 UTC, YahiaBadr commented on routes/api/users.js
> +router.put("/grades/:username",(request,response) =>{
the route mus be descriptive `/addGrade/:username`

2020-01-30 17:48 UTC, YahiaBadr commented on routes/api/users.js
> +    const coursename=request.body.courseName;
camel case `courseName`

2020-01-30 17:48 UTC, YahiaBadr commented on routes/api/users.js
> +    const thegrade=request.body.grade;
the variable name must be the same as the one in the body to be understandable throw the code.
Change `thegrade` to be `grade`

2020-01-30 17:48 UTC, YahiaBadr commented on routes/api/users.js
> +    const credithours=request.body.creditHours
camel case error, `creditHours`.

2020-01-30 17:53 UTC, alynamlaa commented on routes/api/users.js
> +    const coursename=request.body.courseName;
msh fahem ya3ny a3ml eh akhleha ezay?:D

2020-01-30 17:54 UTC, YahiaBadr commented on routes/api/users.js
> +    const coursename=request.body.courseName;
`const courseName`

2020-01-31 20:57 UTC, YahiaBadr commented on routes/api/users.js
> +router.put("/grades/:username",(request,response) =>{
@alynamlaa

2020-01-31 20:57 UTC, YahiaBadr commented on routes/api/users.js
> +            users[i].grades.push({"courseName":courseName, "grade":grade, "creditHours":creditHours})
you don't have to write the field between quotes.

2020-01-31 20:57 UTC, YahiaBadr commented on routes/api/users.js
> +router.put("/addGrades/:username",(request,response) =>{
addGrade!!!! NO (s)

2020-02-04 02:07 UTC, YahiaBadr approved these changes

2020-02-04 02:07 UTC, merged